#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/kfuruglyas/.local/lib/python3.5/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/kfuruglyas/.local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/kfuruglyas/Documents/neunos_project/AberraEtAl2018/orig/x86_64/.libs/libnrnmech.so" "$@"
